In [39]:
import os
import pandas as pd
import wget
import ssl
from datetime import datetime, timedelta
from unidecode import unidecode

data_atual = datetime.now()
data_ontem = data_atual - timedelta(days=1)
data_atual = data_atual.date().strftime('%d-%m-%Y')
data_ontem = data_ontem.date().strftime('%d-%m-%Y')

# DESPESA


try:
    # Desativar a verificação do certificado SSL
    ssl._create_default_https_context = ssl._create_unverified_context

    # URL do arquivo que você deseja baixar
    url = f'https://extrator.sefaz.al.gov.br/DESPESAS/COMPARATIVO-DESPESAS/despesa_empenhado_liquidado_pago_2024_siafe_gerado_em_{data_ontem}.xlsx'
    arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'despesa_empenhado_liquidado_pago_2024_siafe_gerado_em_{data_ontem}.xlsx')
    arquivo_csv = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'despesa_empenhado_liquidado_pago_2024_siafe_gerado_em_{data_ontem}.csv')
    base_despesas_arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024', f'base_despesasxlsx')
    # Baixar o arquivo
    wget.download(url, arquivo)
except: 
     # Desativar a verificação do certificado SSL
    ssl._create_default_https_context = ssl._create_unverified_context

    # URL do arquivo que você deseja baixar
    url = f'https://extrator.sefaz.al.gov.br/DESPESAS/COMPARATIVO-DESPESAS/despesa_empenhado_liquidado_pago_2024_siafe_gerado_em_{data_atual}.xlsx'
    arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'despesa_empenhado_liquidado_pago_2024_siafe_gerado_em_{data_atual}.xlsx')
    arquivo_csv = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'despesa_empenhado_liquidado_pago_2024_siafe_gerado_em_{data_atual}.csv')
    base_despesas_arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024', f'base_despesas.xlsx')
    # Baixar o arquivo
    wget.download(url, arquivo)

# lendo os arquivos
df_novo = pd.read_excel(arquivo)
df_antigo = pd.read_csv('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/5 - VINI/bases/base_despesas_csv.csv', sep=';')
df_uo = pd.read_excel('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/5 - VINI/bases/UG_UO.xlsx', sheet_name='UO')
df_ug = pd.read_excel('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/5 - VINI/bases/UG_UO.xlsx', sheet_name='UG')

# manipulação e merge
df_uo = df_uo.iloc[ : , 1:]
df_ug = df_ug.iloc[ : , 1:]
df_antigo = df_antigo[df_antigo.ANO != 2024]
df = pd.concat([df_antigo, df_novo], axis=0)
df_merge1 = pd.merge(df, df_uo, on='UO', suffixes=('', '_DROP')).filter(regex='^(?!.*_DROP)')
df_merge = pd.merge(df_merge1, df_ug, on='UG', suffixes=('', '_DROP')).filter(regex='^(?!.*_DROP)')
base_despesas = df_merge.copy()
for coluna in df_merge.select_dtypes(include=[object, 'string']):
    base_despesas[coluna] = base_despesas[coluna].astype(str).replace(['\n', '\r', '  ', '   ', '    ', '             '], '', regex=True).apply(lambda x: unidecode(str(x)))
base_despesas.to_excel('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024/base_despesas.xlsx', index=False)


# DOTACAO


try:
    # Desativar a verificação do certificado SSL
    ssl._create_default_https_context = ssl._create_unverified_context

    # URL do arquivo que você deseja baixar
    url = f'https://extrator.sefaz.al.gov.br/DESPESAS/COMPARATIVO-DOTACOES/comparativo_dotacao_despesa_2024_siafe_gerado_em_{data_ontem}.xlsx'
    arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'comparativo_dotacao_despesa_2024_siafe_gerado_em_{data_ontem}.xlsx')
    arquivo_csv = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'comparativo_dotacao_despesa_2024_siafe_gerado_em_{data_ontem}.csv')
    base_dotacao_arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024', f'base_dotacao.csv')

    # Baixar o arquivo
    wget.download(url, arquivo)
    # lendo os arquivos
    df_novo = pd.read_excel(arquivo)
    df_novo.drop(['CODIGO_FAVORECIDO', 'NOME_FAVORECIDO'], axis=1, inplace=True)
except: 
    # Desativar a verificação do certificado SSL
    ssl._create_default_https_context = ssl._create_unverified_context

    # URL do arquivo que você deseja baixar
    url = f'https://extrator.sefaz.al.gov.br/DESPESAS/COMPARATIVO-DOTACOES/comparativo_dotacao_despesa_2024_siafe_gerado_em_{data_atual}.xlsx'
    arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'comparativo_dotacao_despesa_2024_siafe_gerado_em_{data_atual}.xlsx')
    arquivo_csv = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'comparativo_dotacao_despesa_2024_siafe_gerado_em_{data_atual}.csv')
    base_dotacao_arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024', f'base_dotacao.csv')
    # Baixar o arquivo
    wget.download(url, arquivo)
    # lendo os arquivos
    df_novo = pd.read_excel(arquivo)
    df_novo.drop(['CODIGO_FAVORECIDO', 'NOME_FAVORECIDO'], axis=1, inplace=True)

# baixando os arquivos
df_antigo = pd.read_csv('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/5 - VINI/bases/Bases_concatenadas.csv')
df_uo = pd.read_excel('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/5 - VINI/bases/UG_UO.xlsx', sheet_name='UO')
df_ug = pd.read_excel('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/5 - VINI/bases/UG_UO.xlsx', sheet_name='UG')
# manipulação e merge
df_uo = df_uo.iloc[ : , 1:]
df_ug = df_ug.iloc[ : , 1:]
df_antigo = df_antigo[df_antigo.ANO != 2024]
df = pd.concat([df_antigo, df_novo], axis=0)
df_merge1 = pd.merge(df, df_uo, on='UO', suffixes=('', '_DROP')).filter(regex='^(?!.*_DROP)')
df_merge = pd.merge(df_merge1, df_ug, on='UG', suffixes=('', '_DROP')).filter(regex='^(?!.*_DROP)')
base_dotacao = df_merge.copy()
for coluna in df_merge.select_dtypes(include=[object, 'string']):
    base_dotacao[coluna] = base_dotacao[coluna].astype(str).replace(['\n', '\r', '  ', '   ', '    ', '             '], '', regex=True).apply(lambda x: unidecode(str(x)))
base_dotacao.to_csv('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024/base_dotacao.csv', index=False)

# RECEITA


try:
    # Desativar a verificação do certificado SSL
    ssl._create_default_https_context = ssl._create_unverified_context

    # URL do arquivo que você deseja baixar
    url = f'https://extrator.sefaz.al.gov.br/RECEITAS/receita_2024_siafe_gerado_em_{data_ontem}.xlsx'
    arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'receita_2024_siafe_gerado_em_{data_ontem}.xlsx')
    base_receita_arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024', f'receitas_base_18a24.xlsx')

    # Baixar o arquivo
    wget.download(url, arquivo)
    # lendo os arquivos
    df_novo = pd.read_excel(arquivo)
except: 
    # Desativar a verificação do certificado SSL
    ssl._create_default_https_context = ssl._create_unverified_context

    # URL do arquivo que você deseja baixar
    url = f'https://extrator.sefaz.al.gov.br/RECEITAS/receita_2024_siafe_gerado_em_{data_atual}.xlsx'
    arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'receita_2024_siafe_gerado_em_{data_atual}.xlsx')
    base_receita_arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024', f'receitas_base_18a24.xlsx')
    # Baixar o arquivo
    wget.download(url, arquivo)
    # lendo os arquivos
    df_novo = pd.read_excel(arquivo)

# baixando os arquivos
df_antigo = pd.read_excel(base_receita_arquivo)
df_ug = pd.read_excel('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/5 - VINI/bases/UG_UO.xlsx', sheet_name='UG')
# manipulação e merge
df_ug = df_ug.iloc[ : , 1:]
df_antigo = df_antigo[df_antigo.ANO != 2024]
df = pd.concat([df_antigo, df_novo], axis=0)
#df_merge = pd.merge(df, df_ug, on='UG', suffixes=('', '_DROP')).filter(regex='^(?!.*_DROP)')
base_receita = df.copy()
base_receita.to_excel('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024/receitas_base_18a24.xlsx', index=False)

c:\Users\vinicius.ventura\AppData\Local\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\vinicius.ventura\AppData\Local\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\vinicius.ventura\AppData\Local\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [23]:

try:
    # Desativar a verificação do certificado SSL
    ssl._create_default_https_context = ssl._create_unverified_context

    # URL do arquivo que você deseja baixar
    url = f'https://extrator.sefaz.al.gov.br/RECEITAS/receita_2024_siafe_gerado_em_{data_ontem}.xlsx'
    arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'receita_2024_siafe_gerado_em_{data_ontem}.xlsx')
    base_receita_arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024', f'receitas_base_18a24.xlsx')

    # Baixar o arquivo
    wget.download(url, arquivo)
    # lendo os arquivos
    df_novo = pd.read_excel(arquivo)
except: 
    # Desativar a verificação do certificado SSL
    ssl._create_default_https_context = ssl._create_unverified_context

    # URL do arquivo que você deseja baixar
    url = f'https://extrator.sefaz.al.gov.br/RECEITAS/receita_2024_siafe_gerado_em_{data_atual}.xlsx'
    arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/Base python', f'receita_2024_siafe_gerado_em_{data_atual}.xlsx')
    base_receita_arquivo = os.path.join('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024', f'receitas_base_18a24.xlsx')
    # Baixar o arquivo
    wget.download(url, arquivo)
    # lendo os arquivos
    df_novo = pd.read_excel(arquivo)

# baixando os arquivos
df_antigo = pd.read_excel(base_receita_arquivo)
df_ug = pd.read_excel('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/5 - VINI/bases/UG_UO.xlsx', sheet_name='UG')
# manipulação e merge
df_ug = df_ug.iloc[ : , 1:]
df_antigo = df_antigo[df_antigo.ANO != 2024]
df = pd.concat([df_antigo, df_novo], axis=0)
#df_merge = pd.merge(df, df_ug, on='UG', suffixes=('', '_DROP')).filter(regex='^(?!.*_DROP)')
base_receita = df.copy()
base_receita.to_excel('S:/SOP/003 - GERÊNCIA DE ESTUDOS E PROJEÇÕES/DASHBOARDS POWERBI/DESPESAS 2024/receitas_base_18a24.xlsx', index=False)

c:\Users\vinicius.ventura\AppData\Local\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [24]:
df_antigo

,ANO,PODER,COD_TIPO_ADMIN,NOM_TIPO_ADMIN,NOM_ADMINISTRACAO,UG,DESCRICAO_UG,FONTE_MAE,DESCRICAO_FONTE_MAE,FONTE,...,VAL_INICIAL_DEDU_MUNICIPIOS,VAL_INICIAL_DEDU_FUN_MUNI,VAL_INICIAL_LIQUIDO,VAL_INICIAL_ATUALIZADO,VAL_REALIZADO_BRUTO,VAL_REALIZADO_DEDU_FUNDEB,VAL_REALIZADO_DEDU_MUNICIPIO,VAL_REALIZADO_DEDU_OUTROS,VALOR_REALIZADO_LIQUIDO,UG_MNEMONICO
0,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,3526.25,0,0.0,0.0,3526.25,DETRAN/AL
1,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,38303.03,0,0.0,0.0,38303.03,DETRAN/AL
2,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,1223.60,0,0.0,0.0,1223.60,DETRAN/AL
3,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,120422.30,0,0.0,0.0,120422.30,DETRAN/AL
4,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,2362.50,0,0.0,0.0,2362.50,DETRAN/AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43822,2023,EXE,1,ADMINISTRACAO DIRETA,DIRETA,540038,SECRETARIA DE ESTADO DA CIDADANIA E DA PESSOA ...,501,Outros Recursos nao Vinculados,501210021,...,0,0,0.0,0.0,60.42,0,0.0,0.0,60.42,SECDEF
43826,2023,EXE,1,ADMINISTRACAO DIRETA,DIRETA,110009,PROCURADORIA GERAL DO ESTADO,500,Recursos nao Vinculados de Impostos,500000000,...,0,0,0.0,0.0,5614.85,0,0.0,0.0,5614.85,PROC.GERAL ESTADO
43830,2023,EXE,1,ADMINISTRACAO DIRETA,DIRETA,110008,CONTROLADORIA GERAL DO ESTADO,500,Recursos nao Vinculados de Impostos,500000000,...,0,0,0.0,0.0,105.00,0,0.0,0.0,105.00,CONTROLAD.G. ESTADO
43831,2023,EXE,1,ADMINISTRACAO DIRETA,DIRETA,520032,SECRETARIA DE ESTADO DO TURISMO,500,Recursos nao Vinculados de Impostos,500000000,...,0,0,0.0,0.0,31755.43,0,0.0,0.0,31755.43,SETUR
43832,2023,EXE,1,ADMINISTRACAO DIRETA,DIRETA,520032,SECRETARIA DE ESTADO DO TURISMO,500,Recursos nao Vinculados de Impostos,500000000,...,0,0,0.0,0.0,2866.37,0,0.0,0.0,2866.37,SETUR

In [25]:
df_novo

,ANO,PODER,COD_TIPO_ADMIN,NOM_TIPO_ADMIN,NOM_ADMINISTRACAO,UG,DESCRICAO_UG,FONTE_MAE,DESCRICAO_FONTE_MAE,FONTE,...,VAL_INICIAL_DEDU_FUNDEB,VAL_INICIAL_DEDU_MUNICIPIOS,VAL_INICIAL_DEDU_FUN_MUNI,VAL_INICIAL_LIQUIDO,VAL_INICIAL_ATUALIZADO,VAL_REALIZADO_BRUTO,VAL_REALIZADO_DEDU_FUNDEB,VAL_REALIZADO_DEDU_MUNICIPIO,VAL_REALIZADO_DEDU_OUTROS,VALOR_REALIZADO_LIQUIDO
0,2024,EXE,1,ADMINISTRAÇÃO DIRETA,DIRETA,900003,SETORIAL FINANCEIRA,501,Outros Recursos não Vinculados,501000000,...,0,0,0,0.00,0.00,34800.69,0.0,0.0,0.0,34800.69
1,2024,EXE,2,AUTARQUIA,INDIRETA,530538,DEPARTAMENTO DE ESTRADAS DE RODAGEM,752,Recursos Vinculados ao Trânsito,752000000,...,0,0,0,2535496.59,2535496.59,483961.07,0.0,0.0,0.0,483961.07
2,2024,EXE,1,ADMINISTRAÇÃO DIRETA,DIRETA,900003,SETORIAL FINANCEIRA,501,Outros Recursos não Vinculados,501000000,...,0,0,0,0.00,0.00,6737.28,0.0,0.0,0.0,6737.28
3,2024,EXE,1,ADMINISTRAÇÃO DIRETA,DIRETA,510020,SECRETARIA DE ESTADO DA EDUCAÇÃO,550,Transferência do Salário-Educação,550000000,...,0,0,0,0.00,0.00,7146294.80,0.0,0.0,0.0,7146294.80
4,2024,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRÂNSITO DE ALAGOAS,501,Outros Recursos não Vinculados,501000000,...,0,0,0,0.00,0.00,149.34,0.0,0.0,0.0,149.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2879,2024,EXE,1,ADMINISTRAÇÃO DIRETA,DIRETA,340051,SECRETARIA DE ESTADO DE RESSOCIALIZAÇÃO E INCL...,700,Outras Transferências de Convênios ou Instrume...,700210015,...,0,0,0,0.00,0.00,9465.20,0.0,0.0,0.0,9465.20
2880,2024,EXE,1,ADMINISTRAÇÃO DIRETA,DIRETA,520030,"SECRETARIA DE ESTADO DA AGRICULTURA, PECUÁRIA,...",700,Outras Transferências de Convênios ou Instrume...,700190082,...,0,0,0,0.00,0.00,233.86,0.0,0.0,0.0,233.86
2881,2024,EXE,4,FUNDO,DIRETA,540545,FUNDO PARA INFÂNCIA E ADOLESCÊNCIA,759,Recursos Vinculados a Fundos,759000000,...,0,0,0,0.00,0.00,4258.05,0.0,0.0,0.0,4258.05
2882,2024,EXE,4,FUNDO,DIRETA,540534,PROTEÇÃO SOCIAL DA POLICIA MILITAR DO ESTADO D...,500,Recursos não Vinculados de Impostos,500000000,...,0,0,0,0.00,0.00,34503.54,0.0,0.0,0.0,34503.54
2883,2024,EXE,1,ADMINISTRAÇÃO DIRETA,DIRETA,900003,SETORIAL FINANCEIRA,501,Outros Recursos não Vinculados,501000000,...,0,0,0,0.00,0.00,61.12,0.0,0.0,0.0,61.12

In [21]:
41586 + 2884

44470

In [26]:
base_receita

,ANO,PODER,COD_TIPO_ADMIN,NOM_TIPO_ADMIN,NOM_ADMINISTRACAO,UG,DESCRICAO_UG,FONTE_MAE,DESCRICAO_FONTE_MAE,FONTE,...,VAL_INICIAL_DEDU_MUNICIPIOS,VAL_INICIAL_DEDU_FUN_MUNI,VAL_INICIAL_LIQUIDO,VAL_INICIAL_ATUALIZADO,VAL_REALIZADO_BRUTO,VAL_REALIZADO_DEDU_FUNDEB,VAL_REALIZADO_DEDU_MUNICIPIO,VAL_REALIZADO_DEDU_OUTROS,VALOR_REALIZADO_LIQUIDO,UG_MNEMONICO
0,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,3526.25,0.0,0.0,0.0,3526.25,DETRAN/AL
1,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,38303.03,0.0,0.0,0.0,38303.03,DETRAN/AL
2,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,1223.60,0.0,0.0,0.0,1223.60,DETRAN/AL
3,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,120422.30,0.0,0.0,0.0,120422.30,DETRAN/AL
4,2018,EXE,2,AUTARQUIA,INDIRETA,410512,DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS,291,RECURSOS DA ADMINISTRACAO INDIRETA,291000000,...,0,0,0.0,0.0,2362.50,0.0,0.0,0.0,2362.50,DETRAN/AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2879,2024,EXE,1,ADMINISTRAÇÃO DIRETA,DIRETA,340051,SECRETARIA DE ESTADO DE RESSOCIALIZAÇÃO E INCL...,700,Outras Transferências de Convênios ou Instrume...,700210015,...,0,0,0.0,0.0,9465.20,0.0,0.0,0.0,9465.20,NaN
2880,2024,EXE,1,ADMINISTRAÇÃO DIRETA,DIRETA,520030,"SECRETARIA DE ESTADO DA AGRICULTURA, PECUÁRIA,...",700,Outras Transferências de Convênios ou Instrume...,700190082,...,0,0,0.0,0.0,233.86,0.0,0.0,0.0,233.86,NaN
2881,2024,EXE,4,FUNDO,DIRETA,540545,FUNDO PARA INFÂNCIA E ADOLESCÊNCIA,759,Recursos Vinculados a Fundos,759000000,...,0,0,0.0,0.0,4258.05,0.0,0.0,0.0,4258.05,NaN
2882,2024,EXE,4,FUNDO,DIRETA,540534,PROTEÇÃO SOCIAL DA POLICIA MILITAR DO ESTADO D...,500,Recursos não Vinculados de Impostos,500000000,...,0,0,0.0,0.0,34503.54,0.0,0.0,0.0,34503.54,NaN
2883,2024,EXE,1,ADMINISTRAÇÃO DIRETA,DIRETA,900003,SETORIAL FINANCEIRA,501,Outros Recursos não Vinculados,501000000,...,0,0,0.0,0.0,61.12,0.0,0.0,0.0,61.12,NaN